CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR NOT NULL,
    user_email VARCHAR NOT NULL,
    user_login VARCHAR NOT NULL,
    user_birthday DATE NOT NULL,
    CONSTRAINT PK_users PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    CONSTRAINT PK_mpa PRIMARY KEY (mpa_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INT NOT NULL,
    friend_id INT NOT NULL,
    friend_status BOOLEAN NOT NULL,
    CONSTRAINT PK_unique_friends PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS users_likes_films (
    user_id INT NOT NULL,
    film_id INT NOT NULL,
    CONSTRAINT PK_unique_users_likes_films PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS films (
    film_id INT GENERATED BY DEFAULT AS IDENTITY,
    film_name VARCHAR NOT NULL,
    film_description VARCHAR,
    film_release_date DATE NOT NULL,
    film_duration INTEGER NOT NULL,
    film_mpa_id INT NOT NULL,
    FOREIGN KEY (film_mpa_id) REFERENCES mpa(mpa_id),
    CONSTRAINT PK_films PRIMARY KEY (film_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id INT NOT NULL,
    genre_id INT NOT NULL,
    CONSTRAINT PK_unique_film_genre PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    CONSTRAINT PK_genre PRIMARY KEY (genre_id)
);